### PR TITLE
Server re structure

### PR DESCRIPTION
**Pull request by MrEliasen**
## Proposed changes

Completely restructure the server, configs and data to be more in line with common practices. This also helps navigate and find what you are after.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause changes to the I/O signature of existing features.)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help :)! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/MrEliasen/path-to-power-server/blob/master/CONTRIBUTING.md) doc
- [x] Lint pass locally with my changes
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

### CODE REVIEW

**Comment by DennisRas** [comment]
Will do a clean pull and give it a spin tonight before stream to see if there's anything to note.

**Comment by MrEliasen** [comment]
Take your time :), just whenever you have a free moment. No rush.

**Comment by DennisRas** [comment]
Server Install error.
Did some digging and without Python I can't install the server since it attempts to build bcrypt with Python.

Related issues:
https://github.com/mapbox/node-pre-gyp/issues/330
https://github.com/kelektiv/node.bcrypt.js/issues/556
https://github.com/kelektiv/node.bcrypt.js/issues/558
https://github.com/kelektiv/node.bcrypt.js/issues/571
https://github.com/kelektiv/node.bcrypt.js/issues/540
https://stackoverflow.com/questions/48975021/bcrypt1-0-3-install-node-pre-gyp-install-fallback-to-build

Log:
https://gist.github.com/DennisRas/a488341145eac2b83ac51bb83155124a

Possible fix:
Revert bcrypt to version 1.0.2 ?

**Comment by DennisRas** [comment]
Apparently running "npm install" again a second time fixes it.

However I did a hard reset and checked to see if it happened again and it does.
It consistently can't download/install bcrypt on first install without Python.

**Review by DennisRas — CHANGES_REQUESTED** [review]
Question:
Why does the config folder have files in it?
Shouldn't they only exist post-install (being copied from the samples folder)?
Otherwise people are gonna have to merge the config files which is want we want to avoid.

I think the git index/cache is messed up because .gitignore isn't ignoring the config folder even though it's listed in the .gitignore file.
To fix that, I think the following should work in the server directory:

```
git rm -r --cached config
git commit -m "Fixing .gitignore to ignore the config folder"
```

**Comment by DennisRas** [comment]
Weird... Github thinks I requested a change, which I did, but I can't really commit any changes... I think :P
Not sure how this works lol.

_Edit: Figured it out. Just had to commit changes to the branch for them to be included in the PR as usual_

**Comment by MrEliasen** [comment]
All issues should be sorted @DennisRas !

**Pull request merged**
